name: OpenFIRE Builds
on:
  push:
  pull_request:

jobs:
  arduino-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Raspberry Pi Pico'
            fqbn: rpipico
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Raspberry Pi Pico W (USB)'
            fqbn: rpipicow
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Raspberry Pi Pico W (Bluetooth)'
            fqbn: rpipicow
            flags: freq=133,usbstack=tinyusb,opt=Optimize3,ipbtstack=ipv4btcble,wificountry=worldwide
          - name: 'Adafruit ItsyBitsy RP2040'
            fqbn: adafruit_itsybitsy
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Adafruit KB2040'
            fqbn: adafruit_kb2040
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Arduino Nano RP2040 Connect'
            fqbn: arduino_nano_connect
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'VCC-GND YD RP2040'
            fqbn: vccgnd_yd_rp2040
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Waveshare RP2040 Zero'
            fqbn: waveshare_rp2040_zero
            flags: freq=133,usbstack=tinyusb,opt=Optimize3
          - name: 'Generic RP2040'
            fqbn: generic
            flags: freq=133,usbstack=tinyusb,opt=Optimize3

    steps:
      - name: Checkout OpenFIRE-Firmware
        uses: actions/checkout@v4.1.1
      - name: Compile for ${{ matrix.name }}
        uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: rp2040:rp2040:${{ matrix.fqbn }}
          libraries: |
            - source-path: ./
            - name: WiFiNINA
          platforms: |
            - name: rp2040:rp2040
              source-url: https://github.com/SeongGino/arduino-pico/releases/download/3.9.2-fix/package_rp2040_fix_index_orig.json
          sketch-paths: |
            - SamcoEnhanced
          cli-compile-flags: |
            - --export-binaries
              --board-options
              ${{ matrix.flags }}
      # TODO: when USB + Bluetooth is fixed, we won't need these
      - name: Upload Artifact (Non-Pico W)
        if: ${{ matrix.fqbn != 'rpipicow' }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: OpenFIREfw.${{ matrix.fqbn }}.uf2
          path: ${{github.workspace}}/SamcoEnhanced/build/rp2040.rp2040.${{matrix.fqbn}}/SamcoEnhanced.uf2
      - name: Upload Artifact (Pico W USB)
        if: ${{ matrix.name == 'Raspberry Pi Pico W (USB)' }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: OpenFIREfw.${{ matrix.fqbn }}-noBT.uf2
          path: ${{github.workspace}}/SamcoEnhanced/build/rp2040.rp2040.${{matrix.fqbn}}/SamcoEnhanced.uf2
      - name: Upload Artifact (Pico W BT)
        if: ${{ matrix.name == 'Raspberry Pi Pico W (Bluetooth)' }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: OpenFIREfw.${{ matrix.fqbn }}-btBETA.uf2
          path: ${{github.workspace}}/SamcoEnhanced/build/rp2040.rp2040.${{matrix.fqbn}}/SamcoEnhanced.uf2
